# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'SuperHeroes' do
  use_frameworks!

pod 'Alamofire'
pod 'Gloss'

  target 'SuperHeroesTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
