# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'SuperHeroes' do
  use_frameworks!

    pod 'Alamofire'
    pod 'Gloss'
    pod 'Kingfisher'
    pod 'PKHUD', '~> 5.0'

  target 'SuperHeroesTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
